### ISSUE TITLE
Fix issue with `*` following with a `.` (`*hello* .` should be `*hello*.`)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/stepmod-utils#106]
```

Failures:

  1) Stepmod::Utils::Concept when action_schema correctly renders definition
     Failure/Error: expect(parse.to_mn_adoc).to eq(output)
     
       expected: "// STEPmod path:\n=== supported_item\n\ndomain:[STEP resource]\n\nThe *supported_item* allows for th...erence <<ISO_10303-41_2020>> for the complete definition.\n\n\n[.source]\n<<ISO_10303-41_2020>>\n\n"
            got: "// STEPmod path:\n=== supported_item\n\ndomain:[STEP resource]\n\nThe *supported_item* allows for th...erence <<ISO_10303-41_2020>> for the complete definition.\n\n\n[.source]\n<<ISO_10303-41_2020>>\n\n"
     
       (compared using ==)
     
       Diff:
       @@ -3,7 +3,7 @@
        
        domain:[STEP resource]
        
       -The *supported_item* allows for the designation of an *action_directive*, an *action*, or an *action_method*.
       +The *supported_item* allows for the designation of an *action_directive* , an *action* , or an *action_method* .
        
        
        NOTE: This term is incompletely defined in this document.
       
     # ./spec/stepmod/concept_spec.rb:66:in `block (3 levels) in <top (required)>'

  2) Stepmod::Utils::StepmodDefinitionConverter bold whitespace converts html children
     Failure/Error: expect(convert).to eq(output)
     
       expected: "(*\"aic_machining_feature.profile_floor\"\nA *profile_floor* is a type of *shape_aspect* that is the..._floor* are defined in ISO 10303-1814 [5] and define the requirement for *profile_floor*.\n--\n*)\n"
            got: "(*\"aic_machining_feature.profile_floor\"\nA *profile_floor* is a type of *shape_aspect* that is the..._floor* are defined in ISO 10303-1814 [5] and define the requirement for *profile_floor*.\n--\n*)\n"
     
       (compared using ==)
     
       Diff:
       
       @@ -1,8 +1,8 @@
        (*"aic_machining_feature.profile_floor"
       -A *profile_floor* is a type of *shape_aspect* that is the representation of the bottom condition for an *outside_profile* *feature_definition*.
       +A *profile_floor* is a type of *shape_aspect* that is the representation of the bottom condition for an *outside_profile* *feature_definition* .
        [NOTE]
        --
       -A *Profile_floor*, *General_profile_floor* or a *Planar_profile_floor* are defined in ISO 10303-1814 [5] and define the requirement for *profile_floor*.
       +A *Profile_floor* , *General_profile_floor* or a *Planar_profile_floor* are defined in ISO 10303-1814 [5] and define the requirement for *profile_floor*.
        --
        *)
       
     # ./spec/stepmod/stepmod_definition_converter_spec.rb:44:in `block (3 levels) in <top (required)>'

Finished in 1.29 seconds (files took 1.55 seconds to load)
47 examples, 2 failures

Failed examples:

rspec ./spec/stepmod/concept_spec.rb:65 # Stepmod::Utils::Concept when action_schema correctly renders definition
rspec ./spec/stepmod/stepmod_definition_converter_spec.rb:39 # Stepmod::Utils::StepmodDefinitionConverter bold whitespace converts html children
```

**Comment by ronaldtse** [comment]
This is also related to https://github.com/metanorma/iso-10303-2/issues/72.

This is actually a reverse_adoc problem because it applies to AsciiDoc in general.

**Comment by HassanAkbar** [comment]
@ronaldtse  think this issue has been caused due to the fix in [this PR](https://github.com/metanorma/stepmod-utils/issues/105). 
Can I get some context or an example of the issue that was fixed [here](https://github.com/metanorma/stepmod-utils/issues/105)?

**Comment by ronaldtse** [comment]
@HassanAkbar it's actually not that simple:

1. https://github.com/metanorma/stepmod-utils/blob/ccfa5e9dd0bc0070098fc09f2676735476881ab2/lib/stepmod/utils/converters/express_ref.rb#L8
Notice that there is a preceding space even before the PR. Technically, there should not be an additional space front or back. A missing space front or back will lead to disastrous results in AsciiDoc in general (i.e. syntax leaking to content) because of the way the poor manner the parser works.

Because this document had to be submitted to ISO, we take the lesser of two evils -- an extra space before a comma is better than the entire string being broken.

2. https://github.com/metanorma/stepmod-utils/blob/ccfa5e9dd0bc0070098fc09f2676735476881ab2/lib/stepmod/utils/converters/term.rb#L40
We have to strip front and back, because again that the parser is very picky with whitespacing. If there is a whitespace between the line start and content start, the content will be broken.
